# Generated by Django 5.2 on 2026-01-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Liveact', 'verbose_name_plural': 'Liveacts'},
        ),
    ]
