# Generated by Django 5.2 on 2026-01-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
